### PR TITLE
Release 0.2.0

### PR DESCRIPTION
**Pull request by jwoertink**
This release includes a new shard for handling the backtrace display. 

/cc @Sija

### CODE REVIEW

**Comment by jwoertink** [comment]
@Sija there you go!

**Comment by Sija** [comment]
@jwoertink No release though?

**Comment by jwoertink** [comment]
It's there https://github.com/crystal-loot/exception_page/releases/tag/v0.2.0 Are you not able to pull that version? 🤔

**Comment by Sija** [comment]
Oh, there's a tag alright but not the release: 
image

**Pull request merged**
