### PR TITLE
Bump version to 0.1.2

### PR DESCRIPTION
**Pull request by Sija**
New _PATCH_ release with #6 onboard.

### CODE REVIEW

**Review by paulcsmith — APPROVED** [review]
🎉

**Comment by paulcsmith** [comment]
Tagged. Feel free to shards update :)

**Comment by Sija** [comment]
Sweet! Thanks :)

**Comment by Sija** [comment]
It's Alive!!! (;

screen shot 2019-02-05 at 17 12 01

**Comment by paulcsmith** [comment]
Very cool! Love it

**Comment by Sija** [comment]
💡 In the next installment it would probably be a good idea to clamp column width (appending `…` ellipsis) to avoid blowing page layout in case of long shard names.

**Pull request merged**
