### PR TITLE
Use backtracer gem instead of manual parsing

### LINKED ISSUE #8: Broken frame list when compiled with --no-debug flag
screen shot 2019-02-16 at 01 36 44

### PR DESCRIPTION
**Pull request by Sija**
Resolves #8

### CODE REVIEW

**Comment by Sija** [comment]
The build is failing due to unrelated changes.

**Comment by Sija** [comment]
@paulcsmith ping 🏓

**Comment by Sija** [comment]
@paulcsmith Hello?

**Review by jwoertink — APPROVED** [review]
Paul is taking a break from OSS for a bit. I don't have merge privilege, but I think this is probably fine. We can give it a shot and see how it goes 👍

**Comment by jwoertink** [comment]
Now that I have merge privilege, my thought is we can get #23 merged in first, then update this to make sure specs all pass and such. If so, then I'm cool with merging this in.

**Comment by Sija** [comment]
@jwoertink Sounds like a plan 💪

**Comment by jwoertink** [comment]
The way those flow specs work is it looks at the [stack trace on the right](https://user-images.githubusercontent.com/22394/42109073-6e767d06-7baa-11e8-9ec9-0a2afce605be.png) where it says "server.cr", and looks to see that it's on the page. I haven't seen your backtracer shard before, does it change this output? I would assume it would be the same, right?

**Comment by Sija** [comment]
@jwoertink Yeah, I noticed CI fail but didn't had time to fix the specs, will do in the next days.

**Comment by jwoertink** [comment]
Cool. no worries. No rush on it. 👍

**Comment by Sija** [comment]
@jwoertink It's ready to go! :shipit: 

---

> The way those flow specs work is it looks at the [stack trace on the right](https://user-images.githubusercontent.com/22394/42109073-6e767d06-7baa-11e8-9ec9-0a2afce605be.png) where it says "server.cr", and looks to see that it's on the page. I haven't seen your backtracer shard before, does it change this output? I would assume it would be the same, right?

It failed because this PR changes the content, displayed right next to the label for the expanded item - from filename to method name: from `crystal • server.cr` to `crystal • ->`.

**Review by jwoertink — APPROVED** [review]
Cool. Thanks! Let's get this in the hands of some people and try it out.

**Pull request merged**
