### PR TITLE
Bump supported Crystal version to include 1.0

### LINKED ISSUE #20: Crystal 1.0.0 support
Kemal build fails because of this shard hardly depending on Crystal 0.33.0

See the discussion here

https://github.com/kemalcr/kemal/pull/601#issuecomment-804671583

### PR DESCRIPTION
**Pull request by Sija**
Closes #20

### CODE REVIEW

**Comment by waghanza** [comment]
CI  still use `0.36.1`
https://travis-ci.com/github/crystal-loot/exception_page/jobs/493124413#L234

**Comment by Sija** [comment]
@waghanza Travis went south, so I don't consider it noteworthy anymoar.

**Comment by petr-fischer** [comment]
Could this PR be merged?

**Comment by sdogruyol** [comment]
Can we get this merged please? //cc @paulcsmith

**Review by jwoertink — APPROVED** [review]
Paul is taking a break from OSS for a bit, so he probably won't respond, but this is good to me 👍  @Sija feel free to merge when you're ready

**Comment by Sija** [comment]
@jwoertink I would, alas have no rights to do that. Could you pretty please ping @paulcsmith in my name to give me those? Otherwise I'd suggest to move/fork the repo somewhere else.

**Comment by waghanza** [comment]
perhaps @edwardloveall could help up here

**Comment by edwardloveall** [comment]
Hmm, I also don't have merge rights. I'll see what I can do this weekend. Feel free to ping me if I loose track.

**Review by jwoertink — APPROVED** [review]
Uh oh... Somebody gave me a key 😬

**Pull request merged**
